### ISSUE TITLE
doclayout版本暂时有问题，不推荐使用，请问存在什么问题呀?

### ISSUE THREAD

**Issue by vernal0** [RapidAI/RapidLayout#8]
Hi~,我最近在用doclayout做版面分析，看到您今天说doclayout版本暂时有问题，不推荐使用，请问存在什么问题呀?

**Comment by SWHL** [comment]
现在仓库的doclayout模型是最先版本的，后来doclayout官方做了更新，我这里版面分析推理结果较差。
等后续我重新转一份onnx模型，更新过来，再使用吧

**Comment by SWHL** [comment]
已经在`rapid_layout>=0.4.1`中修复，可以再次尝试。

**Comment by vernal0** [comment]
好的，感谢回复
